/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://4bfyz2nxc5cb7fpnosm2cli3da.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-q4bp32linfao7lkogbzhpkmlei",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_2qaCHCZk4",
    "aws_user_pools_web_client_id": "6ug5o2oo8pgg3t1o9e5h81sgee",
    "oauth": {
        "domain": "team06.auth.us-east-1.amazoncognito.com",
        "scope": [
            "email",
            "openid",
            "phone"
        ],
        "redirectSignIn": "https://dev.dl6e1xxl2eyk0.amplifyapp.com",
        "redirectSignOut": "https://dev.dl6e1xxl2eyk0.amplifyapp.com",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "BIRTHDATE",
        "GENDER",
        "PHONE_NUMBER",
        "EMAIL",
        "GIVEN_NAME",
        "FAMILY_NAME",
        "custome:Role",
        "custome:LicenseID",
    ],
    "aws_cognito_mfa_configuration": "OPTIONAL",
    "aws_cognito_mfa_types": [
        "SMS",
        "TOTP"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_UPPERCASE",
            "REQUIRES_NUMBERS",
            "REQUIRES_SYMBOLS"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
